In [1]:
%config IPCompleter.greedy=True
%matplotlib inline

# Import the dependencies.
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Path
from pathlib import Path

In [2]:
# Currently I want to merge two different csv files
# into a larger file to do some analysis on NBA data
#Sources:
#  - https://www.nba.com/stats/players/traditional/?sort=PTS&dir=-1&Season=2019-20&SeasonType=Regular%20Season
#  - https://www.basketball-reference.com/leagues/NBA_2020_per_game.html

stats_nba_file_path = Path("../data/interim/nba-stats-general-traditional-2019-20.csv")
reference_file_path = Path("../data/interim/bbref-general-traditional-2019-20.csv")

stats_nba_df = pd.read_csv(stats_nba_file_path)
reference_df = pd.read_csv(reference_file_path)

In [3]:
stats_nba_df = stats_nba_df.sort_values(by="player_name", key=lambda col: col.str.lower())
stats_nba_df

,season_id,nba_stats_player_id,player_name,team_id,team_abbreviation,age,gp,w,l,w_pct,...,blka,pf,pfd,pts,plus_minus,nba_fantasy_points,dd2,td3,cfid,cfparams
0,2019-20,203932,Aaron Gordon,1610612753,ORL,24.0,62,30,32,0.484,...,0.7,2.0,3.3,14.4,-1.1,31.9,20,1,5,"203932,1610612753"
1,2019-20,1628988,Aaron Holiday,1610612754,IND,23.0,66,42,24,0.636,...,0.4,1.8,1.7,9.5,1.7,19.3,3,0,5,"1628988,1610612754"
2,2019-20,1627846,Abdel Nader,1610612760,OKC,26.0,55,37,18,0.673,...,0.2,1.4,0.9,6.3,-1.5,11.1,0,0,5,"1627846,1610612760"
3,2019-20,1629690,Adam Mokoka,1610612741,CHI,21.0,11,3,8,0.273,...,0.4,1.5,0.4,2.9,4.5,5.5,0,0,5,"1629690,1610612741"
4,2019-20,1629678,Admiral Schofield,1610612764,WAS,23.0,33,9,24,0.273,...,0.1,1.5,0.5,3.0,-1.7,6.3,0,0,5,"1629678,1610612764"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
524,2019-20,203897,Zach LaVine,1610612741,CHI,25.0,60,20,40,0.333,...,1.4,2.2,4.1,25.5,-3.2,40.0,2,0,5,"203897,1610612741"
525,2019-20,1629668,Zach Norvell Jr.,1610612744,GSW,22.0,5,2,3,0.400,...,0.0,0.8,0.2,2.0,-5.4,4.9,0,0,5,"1629668,1610612744"
526,2019-20,1629015,Zhaire Smith,1610612755,PHI,21.0,7,3,4,0.429,...,0.1,0.6,0.3,1.1,-1.4,2.9,0,0,5,"1629015,1610612755"
527,2019-20,1629627,Zion Williamson,1610612740,NOP,19.0,24,11,13,0.458,...,1.6,1.8,5.5,22.5,2.6,33.8,2,0,5,"1629627,1610612740"
528,2019-20,1629597,Zylan Cheatham,1610612740,NOP,24.0,4,2,2,0.500,...,0.0,2.5,0.0,3.0,-7.0,7.3,0,0,5,"1629597,1610612740"

In [4]:
stats_nba_df.dtypes
# I want to conver the column of player_id to string.
stats_nba_df["nba_stats_player_id"] = stats_nba_df["nba_stats_player_id"].astype(str)
stats_nba_df.dtypes

season_id               object
nba_stats_player_id     object
player_name             object
team_id                  int64
team_abbreviation       object
age                    float64
gp                       int64
w                        int64
l                        int64
w_pct                  float64
min                    float64
fgm                    float64
fga                    float64
fg_pct                 float64
fg3m                   float64
fg3a                   float64
fg3_pct                float64
ftm                    float64
fta                    float64
ft_pct                 float64
oreb                   float64
dreb                   float64
reb                    float64
ast                    float64
tov                    float64
stl                    float64
blk                    float64
blka                   float64
pf                     float64
pfd                    float64
pts                    float64
plus_minus             float64
nba_fantasy_points     float64
dd2                      int64
td3                      int64
cfid                     int64
cfparams                object
dtype: object

In [5]:
player_list_name_list = stats_nba_df.loc[:,"player_name"].to_list()
print(len(player_list_name_list))

529

In [6]:
reference_df = reference_df.sort_values(by="player", key=lambda col: col.str.lower())
reference_df

,season_id,bbref_player_id,player,pos,age,team_abbreviation,gp,gs,min,fgm,...,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts
231,2019-20,gordoaa01,Aaron Gordon,PF,24,ORL,62,62,32.5,5.4,...,0.674,1.7,5.9,7.7,3.7,0.8,0.6,1.6,2.0,14.4
289,2019-20,holidaa01,Aaron Holiday,PG,23,IND,66,33,24.5,3.5,...,0.851,0.3,2.0,2.4,3.4,0.8,0.2,1.3,1.8,9.5
448,2019-20,naderab01,Abdel Nader,SF,26,OKC,55,6,15.8,2.2,...,0.773,0.3,1.6,1.8,0.7,0.4,0.4,0.8,1.4,6.3
427,2019-20,mokokad01,Adam Mokoka,SF,21,CHI,11,0,10.2,1.1,...,0.500,0.6,0.3,0.9,0.4,0.4,0.0,0.2,1.5,2.9
539,2019-20,schofad01,Admiral Schofield,PF,22,WAS,33,2,11.2,1.1,...,0.667,0.2,1.2,1.4,0.5,0.2,0.1,0.2,1.5,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
460,2019-20,norveza01,Zach Norvell,SG,22,GSW,3,0,12.0,1.0,...,1.000,0.0,1.7,1.7,1.0,0.7,0.0,1.0,1.3,3.3
459,2019-20,norveza01,Zach Norvell,SG,22,LAL,2,0,2.5,0.0,...,NaN,0.0,0.5,0.5,0.0,0.0,0.0,0.0,0.0,0.0
556,2019-20,smithzh01,Zhaire Smith,SF,20,PHI,7,0,4.6,0.4,...,0.500,0.0,0.3,0.3,0.3,0.4,0.0,0.3,0.6,1.1
639,2019-20,willizi01,Zion Williamson,PF,19,NOP,24,24,27.8,8.8,...,0.640,2.7,3.6,6.3,2.1,0.7,0.4,2.5,1.8,22.5
121,2019-20,cheatzy01,Zylan Cheatham,PF,24,NOP,4,0,12.8,1.5,...,NaN,0.8,1.5,2.3,0.8,0.3,0.3,1.0,2.5,3.0

In [7]:
player_list = reference_df.loc[:,"player"].to_list()
print(len(player_list))

651

In [8]:
# Checking player names from two different sources to match.

def non_match_elements(list_a, list_b):
    non_match = []
    for i in list_a:
        if i not in list_b:
            non_match.append(i)
    return non_match

non_match_head = non_match_elements(player_list_name_list, player_list)
print(f"No match elements: {non_match_head}")
# print(player_list_name_list)
non_match_tail = non_match_elements(player_list, player_list_name_list)
print(f"No match elements: {non_match_tail}")
# print(player_list)

No match elements: ['Alen Smailagic', 'Ante Zizic', 'Anzejs Pasecniks', 'BJ Johnson', 'Boban Marjanovic', 'Bogdan Bogdanovic', 'Bojan Bogdanovic', 'Brian Bowen II', 'Charlie Brown Jr.', 'CJ Miles', 'Cristiano Felicio', 'Danuel House Jr.', 'Dario Saric', 'Davis Bertans', 'Dennis Schroder', 'Derrick Walton Jr.', 'Dzanan Musa', 'Ersan Ilyasova', 'Frank Mason', 'Goran Dragic', 'Harry Giles III', 'James Ennis III', 'JJ Redick', 'Jonas Valanciunas', 'JR Smith', 'Juancho Hernangomez', 'Jusuf Nurkic', 'Kevin Knox II', 'Kristaps Porzingis', 'Lonnie Walker IV', 'Luka Doncic', 'Luka Samanic', 'Marcus Morris Sr.', 'Melvin Frazier Jr.', 'Michael Frazier II', 'Nicolo Melli', 'Nikola Jokic', 'Nikola Vucevic', 'Otto Porter Jr.', 'Robert Williams III', 'Skal Labissiere', 'Svi Mykhailiuk', 'Timothe Luwawu-Cabarrot', 'Tomas Satoransky', 'Vlatko Cancar', 'Wes Iwundu', 'Willy Hernangomez', 'Zach Norvell Jr.']
No match elements: ['Alen Smailagić', 'Ante Žižić', 'Anžejs Pasečņiks', 'B.J. Johnson', 'Boban Marjanović', 'Bogdan Bogdanović', 'Bojan Bogdanović', 'Brian Bowen', 'C.J. Miles', 'Charlie Brown', 'Cristiano Felício', 'Danuel House', 'Dario Šarić', 'Dennis Schröder', 'Derrick Walton', 'Derrick Walton', 'Derrick Walton', 'Dāvis Bertāns', 'Džanan Musa', 'Ersan İlyasova', 'Frank Mason III', 'Goran Dragić', 'Harry Giles', 'J.J. Redick', 'J.R. Smith', 'James Ennis', 'James Ennis', 'James Ennis', 'Jonas Valančiūnas', 'Juan Hernangómez', 'Juan Hernangómez', 'Juan Hernangómez', 'Jusuf Nurkić', 'Kevin Knox', 'Kristaps Porziņģis', 'Lonnie Walker', 'Luka Dončić', 'Luka Šamanić', 'Marcus Morris', 'Marcus Morris', 'Marcus Morris', 'Melvin Frazier', 'Michael Frazier', 'Nicolò Melli', 'Nikola Jokić', 'Nikola Vučević', 'Otto Porter', 'Robert Williams', 'Skal Labissière', 'Sviatoslav Mykhailiuk', 'Timothé Luwawu-Cabarrot', 'Tomáš Satoranský', 'Vlatko Čančar', 'Wesley Iwundu', 'Willy Hernangómez', 'Zach Norvell', 'Zach Norvell', 'Zach Norvell']

In [9]:
# How to select rows with NaN in particular column?
# df.loc[df['Col2'].isnull()]
na_reference_df = reference_df.loc[reference_df["player"].isnull()]
na_reference_df

Empty DataFrame
Columns: [season_id, bbref_player_id, player, pos, age, team_abbreviation, gp, gs, min, fgm, fga, fg_pct, fg3m, fg3a, fg3_pct, 2p, 2pa, 2p%, efg%, ftm, fta, ft_pct, oreb, dreb, reb, ast, stl, blk, tov, pf, pts]
Index: []

[0 rows x 31 columns]

In [10]:
# Dropped rows where the column Player is equal to NaN
filter_reference_df = reference_df.loc[~reference_df["player"].isin([np.nan])]
filter_reference_df

,season_id,bbref_player_id,player,pos,age,team_abbreviation,gp,gs,min,fgm,...,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts
231,2019-20,gordoaa01,Aaron Gordon,PF,24,ORL,62,62,32.5,5.4,...,0.674,1.7,5.9,7.7,3.7,0.8,0.6,1.6,2.0,14.4
289,2019-20,holidaa01,Aaron Holiday,PG,23,IND,66,33,24.5,3.5,...,0.851,0.3,2.0,2.4,3.4,0.8,0.2,1.3,1.8,9.5
448,2019-20,naderab01,Abdel Nader,SF,26,OKC,55,6,15.8,2.2,...,0.773,0.3,1.6,1.8,0.7,0.4,0.4,0.8,1.4,6.3
427,2019-20,mokokad01,Adam Mokoka,SF,21,CHI,11,0,10.2,1.1,...,0.500,0.6,0.3,0.9,0.4,0.4,0.0,0.2,1.5,2.9
539,2019-20,schofad01,Admiral Schofield,PF,22,WAS,33,2,11.2,1.1,...,0.667,0.2,1.2,1.4,0.5,0.2,0.1,0.2,1.5,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
460,2019-20,norveza01,Zach Norvell,SG,22,GSW,3,0,12.0,1.0,...,1.000,0.0,1.7,1.7,1.0,0.7,0.0,1.0,1.3,3.3
459,2019-20,norveza01,Zach Norvell,SG,22,LAL,2,0,2.5,0.0,...,NaN,0.0,0.5,0.5,0.0,0.0,0.0,0.0,0.0,0.0
556,2019-20,smithzh01,Zhaire Smith,SF,20,PHI,7,0,4.6,0.4,...,0.500,0.0,0.3,0.3,0.3,0.4,0.0,0.3,0.6,1.1
639,2019-20,willizi01,Zion Williamson,PF,19,NOP,24,24,27.8,8.8,...,0.640,2.7,3.6,6.3,2.1,0.7,0.4,2.5,1.8,22.5
121,2019-20,cheatzy01,Zylan Cheatham,PF,24,NOP,4,0,12.8,1.5,...,NaN,0.8,1.5,2.3,0.8,0.3,0.3,1.0,2.5,3.0

In [11]:
# basketball Reference Data also has duplicate Player values since they were
# on different teams through the season but same person.
filter_reference_df.duplicated(subset=['bbref_player_id'])

231    False
289    False
448    False
427    False
539    False
       ...
460     True
459     True
556    False
639    False
121    False
Length: 651, dtype: bool

In [12]:
# basketball Reference Data also has duplicate Player values since they were
# on different teams through the season but same person.

# We need to select the data we will be using for deduplication from our baseketball reference data.

# take the player name, id, team and fields we will use for deduplication from bbref data
# bbref_base_data = filter_reference_df[["Player", "id", "Team", "Field Goal Attempts", "Total Rebounds", "Assists"]].groupby(
#     by="id").apply(deduplicate_traded_players)

# We also need to deduplicate players who played for multiple teams in a single year on

# Basketball reference contains multiple rows for players who have played on multiple teams.
# we only care about the season total for the player so we must deduplicate the rows (selected Team = TOT)
def deduplicate_traded_players(group):
    if len(group) > 1:
        return group[group["team_abbreviation"] == "TOT"]
    return group

deduplicate_df = filter_reference_df[["bbref_player_id", "player", "team_abbreviation", "fga", "reb", "ast"]].groupby(
    by="bbref_player_id").apply(deduplicate_traded_players)
deduplicate_df

,,bbref_player_id,player,team_abbreviation,fga,reb,ast
bbref_player_id,,,,,,,
adamsst01,0,adamsst01,Steven Adams,OKC,7.6,9.3,2.3
adebaba01,1,adebaba01,Bam Adebayo,MIA,11.0,10.2,5.1
aldrila01,2,aldrila01,LaMarcus Aldridge,SAS,15.0,7.4,2.4
alexaky01,3,alexaky01,Kyle Alexander,MIA,1.0,1.5,0.0
alexani01,4,alexani01,Nickeil Alexander-Walker,NOP,5.7,1.8,1.9
...,...,...,...,...,...,...,...
youngtr01,646,youngtr01,Trae Young,ATL,20.8,4.3,9.3
zelleco01,647,zelleco01,Cody Zeller,CHO,8.3,7.1,1.5
zellety01,648,zellety01,Tyler Zeller,SAS,2.0,2.0,0.0
zizican01,649,zizican01,Ante Žižić,CLE,3.3,3.0,0.3
zubaciv01,650,zubaciv01,Ivica Zubac,LAC,5.3,7.5,1.1

In [13]:
# take the player name, id, and fields we will use for deduplication from stats.nba.com data
nba_base_data = stats_nba_df[["nba_stats_player_id", "player_name", "team_abbreviation", "fga", "reb", "ast"]]
nba_base_data

    nba_stats_player_id        player_name team_abbreviation   fga  reb  ast
0                203932       Aaron Gordon               ORL  12.4  7.7  3.7
1               1628988      Aaron Holiday               IND   8.5  2.4  3.4
2               1627846        Abdel Nader               OKC   4.8  1.8  0.7
3               1629690        Adam Mokoka               CHI   2.5  0.9  0.4
4               1629678  Admiral Schofield               WAS   2.8  1.4  0.5
..                  ...                ...               ...   ...  ...  ...
524              203897        Zach LaVine               CHI  20.0  4.8  4.2
525             1629668   Zach Norvell Jr.               GSW   2.4  1.2  0.6
526             1629015       Zhaire Smith               PHI   1.6  0.3  0.3
527             1629627    Zion Williamson               NOP  15.0  6.3  2.1
528             1629597     Zylan Cheatham               NOP   2.3  2.3  0.8

[529 rows x 6 columns]

In [14]:
# Perform a full outer join on the two dataframes. This allows us to get all of the exact matches
name_matches = deduplicate_df.merge(nba_base_data,
                                     left_on=["player", "team_abbreviation", "fga", "reb", "ast"],
                                     right_on=["player_name", "team_abbreviation", "fga", "reb", "ast"], how="outer")

# take all of the exact matches and rename the columns, we only care about player name and id from each source
name_matches_ids = name_matches.dropna()
name_matches_ids = name_matches_ids[["bbref_player_id", "player", "nba_stats_player_id", "player_name"]]
name_matches_ids.columns = ["bbref_name", "bbref_id", "nba_name", "nba_id"]
name_matches

,bbref_player_id,player,team_abbreviation,fga,reb,ast,nba_stats_player_id,player_name
0,adamsst01,Steven Adams,OKC,7.6,9.3,2.3,203500,Steven Adams
1,adebaba01,Bam Adebayo,MIA,11.0,10.2,5.1,1628389,Bam Adebayo
2,aldrila01,LaMarcus Aldridge,SAS,15.0,7.4,2.4,200746,LaMarcus Aldridge
3,alexaky01,Kyle Alexander,MIA,1.0,1.5,0.0,1629734,Kyle Alexander
4,alexani01,Nickeil Alexander-Walker,NOP,5.7,1.8,1.9,1629638,Nickeil Alexander-Walker
...,...,...,...,...,...,...,...,...
681,NaN,NaN,ORL,4.5,2.5,1.2,1628411,Wes Iwundu
682,NaN,NaN,DAL,5.6,5.8,1.3,1626161,Willie Cauley-Stein
683,NaN,NaN,CHA,4.5,4.3,0.9,1626195,Willy Hernangomez
684,NaN,NaN,BKN,5.2,4.1,1.1,201163,Wilson Chandler
685,NaN,NaN,GSW,2.4,1.2,0.6,1629668,Zach Norvell Jr.

In [15]:
# Take all of the rows from the full outer join that have null values. These are the cases where no match was found.
non_matches = name_matches[name_matches.isnull().any(axis=1)]

# take all of the bbref data from non_matches
bbref_non_matches = non_matches[["player", "bbref_player_id", "team_abbreviation", "fga", "reb", "ast"]].dropna()

# take all of the stats.nba data from the non_matches
nba_non_matches = non_matches[["player_name", "nba_stats_player_id", "team_abbreviation", "fga", "reb", "ast"]].dropna()

In [16]:
bbref_non_matches

              player bbref_player_id team_abbreviation   fga   reb  ast
6      Jarrett Allen       allenja01               BRK   6.6   9.6  1.6
9    Justin Anderson       anderju01               BRK   3.8   2.1  0.8
18      Trevor Ariza       arizatr01               TOT   6.1   4.6  1.7
20     Deandre Ayton       aytonde01               PHO  14.9  11.5  1.9
21      Dwayne Bacon       bacondw01               CHO   6.3   2.6  1.3
..               ...             ...               ...   ...   ...  ...
514  Marvin Williams       willima02               TOT   4.6   3.2  1.0
516  Robert Williams       williro04               BOS   3.0   4.4  0.9
519  Justise Winslow       winslju01               MIA  11.7   6.6  4.0
525      Cody Zeller       zelleco01               CHO   8.3   7.1  1.5
527       Ante Žižić       zizican01               CLE   3.3   3.0  0.3

[157 rows x 6 columns]

In [17]:
nba_non_matches

,player_name,nba_stats_player_id,team_abbreviation,fga,reb,ast
529,Alec Burks,202692,PHI,11.6,4.3,2.9
530,Alen Smailagic,1629346,GSW,2.9,1.9,0.9
531,Alex Len,203458,SAC,5.8,5.8,0.9
532,Allen Crabbe,203459,MIN,4.8,2.1,0.9
533,Andre Drummond,203083,CLE,13.8,15.2,2.7
...,...,...,...,...,...,...
681,Wes Iwundu,1628411,ORL,4.5,2.5,1.2
682,Willie Cauley-Stein,1626161,DAL,5.6,5.8,1.3
683,Willy Hernangomez,1626195,CHA,4.5,4.3,0.9
684,Wilson Chandler,201163,BKN,5.2,4.1,1.1
685,Zach Norvell Jr.,1629668,GSW,2.4,1.2,0.6

In [18]:
from fuzzywuzzy import fuzz

def check_names_fuzzy_match(row):
    row["name_match"] = fuzz.partial_ratio(row["player"], row["player_name"]) > 60
    return row

possible_matches = bbref_non_matches.merge(nba_non_matches,
                                     left_on=["team_abbreviation", "fga", "reb", "ast"],
                                     right_on=["team_abbreviation", "fga", "reb", "ast"], how="outer").apply(check_names_fuzzy_match, axis=1)

#print out any misses
print(possible_matches[possible_matches["name_match"] != True].head(10))

fuzzy_matches = possible_matches[possible_matches["name_match"]][["bbref_player_id", "player", "nba_stats_player_id", "player_name"]]

# Give the dataframe column names
fuzzy_matches.columns = ["bbref_id", "bbref_name", "nba_id", "nba_name"]

Empty DataFrame
Columns: [player, bbref_player_id, team_abbreviation_x, fga, reb, ast, player_name, nba_stats_player_id, team_abbreviation_y, name_match]
Index: []

C:\ProgramData\Anaconda3\lib\site-packages\fuzzywuzzy\fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')

In [22]:
# merge our fuzzy matched ids with our exact match ids
all_matches = fuzzy_matches.append(name_matches_ids)

# write to csv
all_matches.to_csv("../data/processed/nba-stats-bbref-general-traditional-2019-20.csv", index=False)
all_matches

    bbref_name               bbref_id nba_name                 nba_id
0    allenja01          Jarrett Allen  1628386          Jarrett Allen
1    anderju01        Justin Anderson  1626147        Justin Anderson
2    arizatr01           Trevor Ariza     2772           Trevor Ariza
3    aytonde01          Deandre Ayton  1629028          Deandre Ayton
4    bacondw01           Dwayne Bacon  1628407           Dwayne Bacon
..         ...                    ...      ...                    ...
522  wrighju02  Justin Wright-Foreman  1629625  Justin Wright-Foreman
523  youngth01         Thaddeus Young   201152         Thaddeus Young
524  youngtr01             Trae Young  1629027             Trae Young
526  zellety01           Tyler Zeller   203092           Tyler Zeller
528  zubaciv01            Ivica Zubac  1627826            Ivica Zubac

[529 rows x 4 columns]